### ISSUE TITLE
This depends on bspwm

### ISSUE THREAD

**Issue by FunctionalHacker** [nagy135/subtube#1]
Bspwm is not listed in the dependencies but it seems that the script calls bspc. Is there a way to get rid of that line completely or maybe accomplish that in a WM agnostic way?

**Comment by nagy135** [comment]
all it does is make it's sxiv floating, follow me on workspaces and set size ...if you comment the line it uses sxiv default ....i will add some divide, for now just comment it out

as i said...this script was mainly for my own use, so if you see some other forgotten dependecy, lemme know ...its quite usefull tool

**Comment by FunctionalHacker** [comment]
Thanks for the info. Sorry if I came across negative, I find your tool very useful indeed. I just wanted to address this to help people who come across this repository in the future. Maybe you should add what you just wrote here somewhere in the readme?

**Comment by nagy135** [comment]
this [commit](https://github.com/nagy135/subtube/commit/57910b97140e5610e148878087fbf8a0f6f361bb) should solve your issue ....

no apology needed, you are absolutely right ...i should mention it
I m happy for any feedback :)
