### ISSUE TITLE
Add wmctrl as dependency

### ISSUE THREAD

**Issue by WitherCubes** [nagy135/subtube#3]
The title of this issue explains it. I don't know if this package is needed for Wayland, but when I exited sxiv it was showing an error that wmctrl was missing. I am not sure that this is an issue or not. If this is not an issue, please be free to criticize me and close this issue.

**Comment by nagy135** [comment]
Yes you are right, i never use it on cli only with binds so i never saw after i switched to wayland. Its only used to detect if you use bspwm (which is silly reason to have extra dependency) and on wayland at least it should not be there since its x11 wm...will fix shortly (vacation)
